### PR TITLE
Fix for breaking changes in core for Ampere/Volt sensors

### LINKED ISSUE #500: Somfy sensors unavailable after upgrade to 2021.8 beta
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

After upgrading to the 2021.8 beta HA core.  Sensors such as the temperature and light sensors connected to the Somfy Tahoma are unavailable and the following is listed in the log.

### What version of this integration (ha-tahoma) has the issue?

2.5.1

### What version of Home Assistant Core has the issue?

core-2021.8.0b5

### Which gateway / hub do you use?

Tahoma V2 Hub

### Device model

LuminanceSensor and TemperatureSensor

### Device type

io:LightIOSystemSensor and io:TemperatureIOSystemSensor

### Additional information

_No response_

### Relevant log output

```shell
Logger: homeassistant.setup
Source: setup.py:311
First occurred: 8:04:23 AM (1 occurrences)
Last logged: 8:04:23 AM

Unable to prepare setup for platform tahoma.sensor: Platform not found (cannot import name 'ELECTRICAL_CURRENT_AMPERE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).
```

### PR DESCRIPTION
**Pull request by iMicknl**
Fixes #500

### CODE REVIEW

**Review by tetienne — APPROVED** [review]

File: custom_components/tahoma/sensor.py [hunk 1]
```diff
@@ -98,7 +107,7 @@
     "meters_seconds": SPEED_METERS_PER_SECOND,
 }
 
-UNITS_BY_DEVICE_CLASS = {  # Remove after 2021.4 release
+UNITS_BY_DEVICE_CLASS = {
```
[the remark this answers is not in the document]
Comment (iMicknl) [reply custom_components/tahoma/sensor.py:110]: I had a look and it seems this shouldn't be removed... Previously we set `CONCENTRATION_PARTS_PER_MILLION` ourselves, but they are already imported from core... Seems that I forgot to remove this comment in the past.

And as far as I know, even when you set a device class, you would still need to set the unit.

[the remark this answers is not in the document]
Comment (tetienne) [reply custom_components/tahoma/sensor.py:110]: Thx
