### PR TITLE
Fix number entity in 2022.1.0dev

### LINKED ISSUE #665: OverkizNumber' object has no attribute '_attr_min_value'
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

see error log

### What version of this integration (ha-tahoma) has the issue?

2.9.3

### What version of Home Assistant Core has the issue?

2022.1.0dev

### Which gateway / hub do you use?

Somfy  Tahoma

### Device model

_No response_

### Home Assistant log

```shell
2021-12-07 13:51:38 ERROR (MainThread) [homeassistant.components.number] Error adding entities for domain number with platform tahoma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 513, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 114, in capability_attributes
    ATTR_MIN: self.min_value,
  File "/config/custom_components/tahoma/number.py", line 82, in min_value
    return self.entity_description.min_value or self._attr_min_value
AttributeError: 'OverkizNumber' object has no attribute '_attr_min_value'
2021-12-07 13:51:38 ERROR (MainThread) [homeassistant.components.number] Error while setting up tahoma platform for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 513, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 114, in capability_attributes
    ATTR_MIN: self.min_value,
  File "/config/custom_components/tahoma/number.py", line 82, in min_value
    return self.entity_description.min_value or self._attr_min_value
AttributeError: 'OverkizNumber' object has no attribute '_attr_min_value'
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by iMicknl**
Fixes #665 

Broken by https://github.com/home-assistant/core/pull/61100.

(requires 2022.1.0dev)

<a href="https://gitpod.io/#https://github.com/iMicknl/ha-tahoma/pull/667"></a>

### CODE REVIEW

**Comment by Mariusthvdb** [comment]
cool, Ill edit the files manually, and see if all is well.
thanks for the swift response

**Comment by tetienne** [comment]
Indeed, nice clean up.

**Review by tetienne — APPROVED** [review]

**Review by Quentame — APPROVED** [review]
Looks nice

**Comment by Mariusthvdb** [comment]
is there any chance this can get merged some time soon? Since all checks have passed, maybe another look is all that is needed? would be hugely appreciated .
thanks!

**Comment by iMicknl** [comment]
> is there any chance this can get merged some time soon? Since all checks have passed, maybe another look is all that is needed? would be hugely appreciated . thanks!

No. And I thought I made myself clear in https://github.com/iMicknl/ha-tahoma/issues/665 already. This fix will break current functionality in 2021.12, thus we will merge this only after 2022.1 is released.
If you don't want to face issues, don't run beta versions on your production instance, or merge the required change in your integration.

I will sometimes hit 'update branch' on this pull request, so you can use this version manually with the latest changes of this integration, but more than that I can't do.
