### ISSUE TITLE
Somfy sensors unavailable after upgrade to 2021.8 beta

### ISSUE THREAD

**Issue by Nodezero1** [iMicknl/ha-tahoma#500]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

After upgrading to the 2021.8 beta HA core.  Sensors such as the temperature and light sensors connected to the Somfy Tahoma are unavailable and the following is listed in the log.

### What version of this integration (ha-tahoma) has the issue?

2.5.1

### What version of Home Assistant Core has the issue?

core-2021.8.0b5

### Which gateway / hub do you use?

Tahoma V2 Hub

### Device model

LuminanceSensor and TemperatureSensor

### Device type

io:LightIOSystemSensor and io:TemperatureIOSystemSensor

### Relevant log output

```shell
Logger: homeassistant.setup
Source: setup.py:311
First occurred: 8:04:23 AM (1 occurrences)
Last logged: 8:04:23 AM

Unable to prepare setup for platform tahoma.sensor: Platform not found (cannot import name 'ELECTRICAL_CURRENT_AMPERE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).
```

**Comment by iMicknl** [comment]
Thanks for reporting, @Nodezero1!

It seems that `ELECTRICAL_CURRENT_AMPERE` is renamed to `ELECTRIC_CURRENT_AMPERE` in https://github.com/home-assistant/core/pull/53243. We will fix this in the coming days :-).

**Comment by iMicknl** [comment]
Could you give https://github.com/iMicknl/ha-tahoma/archive/refs/heads/fix/500.zip a try? Extract this file and place `custom_components/tahoma` in your `custom_components` folder.

This should fix your issues with the latest beta. :-)

**Comment by Nodezero1** [comment]
Thanks, that did the trick!
